import express from 'express'
import db from '../db.js'
import { logger } from '../logger.js'

const router = express.Router()

// Cache headers — 24h CDN, regenerated by Vercel ISR daily anyway
function setCache(res) {
  res.set('Cache-Control', 'public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800')
}

// GET /api/v1/sitemap/nurseries
// Returns all active nursery URNs (paginated through Supabase 1000-row limit)
router.get('/nurseries', async (req, res, next) => {
  try {
    const all = []
    const PAGE = 1000
    let offset = 0
    while (true) {
      const { data, error } = await db
        .from('nurseries')
        .select('urn')
        .eq('registration_status', 'Active')
        .range(offset, offset + PAGE - 1)
      if (error) throw error
      if (!data || data.length === 0) break
      all.push(...data.map(r => r.urn))
      if (data.length < PAGE) break
      offset += PAGE
    }
    setCache(res)
    res.json({ urns: all, count: all.length })
  } catch (err) {
    logger.error({ err: err.message }, 'sitemap: nurseries failed')
    next(err)
  }
})

// GET /api/v1/sitemap/districts
router.get('/districts', async (req, res, next) => {
  try {
    const { data, error } = await db
      .from('postcode_areas')
      .select('postcode_district')
      .gt('nursery_count_total', 0)
    if (error) throw error
    setCache(res)
    res.json({
      districts: (data || []).map(r => r.postcode_district),
      count: data?.length || 0,
    })
  } catch (err) {
    logger.error({ err: err.message }, 'sitemap: districts failed')
    next(err)
  }
})

export default router
